spring:
  application:
    name: Spring_Boot_Actuators
  datasource:
    url: jdbc:mysql://localhost:3306/sbms36
    username: root
    password: WJ28@krhps
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans
  endpoint:
    shutdown:
      enabled: true